<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.1.1deb5ubuntu1
 */

/**
 * Database `quotes`
 */

/* `quotes`.`quotes` */
return array(
  array('id' => '1','quote' => 'Anyone who stops learning is old'),
  array('id' => '2','quote' => 'Wrinkles should merely indicate where smiles have been.'),
  array('id' => '3','quote' => 'True terror is to wake up one morning and discover that your high school class is running the country.'),
  array('id' => '4','quote' => 'A diplomat is a man who always remembers a woman\'s birthday but never remembers her age.'),
  array('id' => '5','quote' => 'As I grow older'),
  array('id' => '6','quote' => 'How incessant and great are the ills with which a prolonged old age is replete.'),
  array('id' => '7','quote' => 'Old age'),
  array('id' => '8','quote' => 'Old age has deformities enough of its own. It should never add to them the deformity of vice.'),
  array('id' => '9','quote' => 'Nobody grows old merely by living a number of years. We grow old by deserting our ideals. Years may wrinkle the skin'),
  array('id' => '10','quote' => 'An archaeologist is the best husband a woman can have. The older she gets the more interested he is in her.'),
  array('id' => '11','quote' => 'All diseases run into one'),
  array('id' => '12','quote' => 'Bashfulness is an ornament to youth'),
  array('id' => '13','quote' => 'Like everyone else who makes the mistake of getting older'),
  array('id' => '14','quote' => 'Age appears to be best in four things old wood best to burn'),
  array('id' => '15','quote' => 'None are so old as those who have outlived enthusiasm.'),
  array('id' => '16','quote' => 'Every man over forty is a scoundrel.'),
  array('id' => '17','quote' => 'Forty is the old age of youth fifty the youth of old age.'),
  array('id' => '18','quote' => 'You can\'t help getting older'),
  array('id' => '19','quote' => 'Alas'),
  array('id' => '20','quote' => 'Youth is when you\'re allowed to stay up late on New Year\'s Eve. Middle age is when you\'re forced to.'),
  array('id' => '21','quote' => 'Old age is like everything else. To make a success of it'),
  array('id' => '22','quote' => 'A comfortable old age is the reward of a well-spent youth. Instead of its bringing sad and melancholy prospects of decay'),
  array('id' => '23','quote' => 'A man growing old becomes a child again.'),
  array('id' => '24','quote' => 'I will never be an old man. To me'),
  array('id' => '25','quote' => 'Age considers youth ventures.'),
  array('id' => '26','quote' => 'What most persons consider as virtue'),
  array('id' => '27','quote' => 'Age is a very high price to pay for maturity.'),
  array('id' => '28','quote' => 'Old age is no place for sissies.'),
  array('id' => '29','quote' => 'I don\'t feel old. I don\'t feel anything till noon. That\'s when it\'s time for my nap.'),
  array('id' => '30','quote' => 'As I approve of a youth that has something of the old man in him'),
  array('id' => '31','quote' => 'I don\'t believe one grows older. I think that what happens early on in life is that at a certain age one stands still and stagnates.'),
  array('id' => '32','quote' => 'Advice in old age is foolish for what can be more absurd than to increase our provisions for the road the nearer we approach to our journey\'s end.'),
  array('id' => '33','quote' => 'When grace is joined with wrinkles'),
  array('id' => '34','quote' => 'It takes a long time to become young.'),
  array('id' => '35','quote' => 'After thirty'),
  array('id' => '36','quote' => 'There is a fountain of youth: it is your mind'),
  array('id' => '37','quote' => 'Age is not a particularly interesting subject. Anyone can get old. All you have to do is live long enough.'),
  array('id' => '38','quote' => 'Old minds are like old horses you must exercise them if you wish to keep them in working order.'),
  array('id' => '39','quote' => 'Forty is the old age of youth'),
  array('id' => '40','quote' => 'Youth is the gift of nature'),
  array('id' => '41','quote' => 'Preparation for old age should begin not later than one\'s teens. A life which is empty of purpose until 65 will not suddenly become filled on retirement.'),
  array('id' => '42','quote' => 'There is always some specific moment when we become aware that our youth is gone but'),
  array('id' => '43','quote' => 'Growing old is no more than a bad habit which a busy person has no time to form.'),
  array('id' => '44','quote' => 'As long as any adult thinks that he'),
  array('id' => '45','quote' => 'Old age is fifteen years older than I am.'),
  array('id' => '46','quote' => 'Aging is not lost youth but a new stage of opportunity and strength.'),
  array('id' => '47','quote' => 'The great secret that all old people share is that you really haven\'t changed in seventy or eighty years. Your body changes'),
  array('id' => '48','quote' => 'The trick is growing up without growing old.'),
  array('id' => '49','quote' => 'Old age comes on suddenly'),
  array('id' => '50','quote' => 'I think your whole life shows in your face and you should be proud of that.'),
  array('id' => '51','quote' => 'Age is an issue of mind over matter. If you don\'t mind'),
  array('id' => '52','quote' => 'Anyone who stops learning is old'),
  array('id' => '53','quote' => 'Wrinkles should merely indicate where smiles have been.'),
  array('id' => '54','quote' => 'True terror is to wake up one morning and discover that your high school class is running the country.'),
  array('id' => '55','quote' => 'A diplomat is a man who always remembers a woman\'s birthday but never remembers her age.'),
  array('id' => '56','quote' => 'As I grow older'),
  array('id' => '57','quote' => 'How incessant and great are the ills with which a prolonged old age is replete.'),
  array('id' => '58','quote' => 'Old age'),
  array('id' => '59','quote' => 'Old age has deformities enough of its own. It should never add to them the deformity of vice.'),
  array('id' => '60','quote' => 'Nobody grows old merely by living a number of years. We grow old by deserting our ideals. Years may wrinkle the skin'),
  array('id' => '61','quote' => 'An archaeologist is the best husband a woman can have. The older she gets the more interested he is in her.'),
  array('id' => '62','quote' => 'All diseases run into one'),
  array('id' => '63','quote' => 'Bashfulness is an ornament to youth'),
  array('id' => '64','quote' => 'Like everyone else who makes the mistake of getting older'),
  array('id' => '65','quote' => 'Age appears to be best in four things old wood best to burn'),
  array('id' => '66','quote' => 'None are so old as those who have outlived enthusiasm.'),
  array('id' => '67','quote' => 'Every man over forty is a scoundrel.'),
  array('id' => '68','quote' => 'Forty is the old age of youth fifty the youth of old age.'),
  array('id' => '69','quote' => 'You can\'t help getting older'),
  array('id' => '70','quote' => 'Alas'),
  array('id' => '71','quote' => 'Youth is when you\'re allowed to stay up late on New Year\'s Eve. Middle age is when you\'re forced to.'),
  array('id' => '72','quote' => 'Old age is like everything else. To make a success of it'),
  array('id' => '73','quote' => 'A comfortable old age is the reward of a well-spent youth. Instead of its bringing sad and melancholy prospects of decay'),
  array('id' => '74','quote' => 'A man growing old becomes a child again.'),
  array('id' => '75','quote' => 'I will never be an old man. To me'),
  array('id' => '76','quote' => 'Age considers youth ventures.'),
  array('id' => '77','quote' => 'What most persons consider as virtue'),
  array('id' => '78','quote' => 'Age is a very high price to pay for maturity.'),
  array('id' => '79','quote' => 'Old age is no place for sissies.'),
  array('id' => '80','quote' => 'I don\'t feel old. I don\'t feel anything till noon. That\'s when it\'s time for my nap.'),
  array('id' => '81','quote' => 'As I approve of a youth that has something of the old man in him'),
  array('id' => '82','quote' => 'I don\'t believe one grows older. I think that what happens early on in life is that at a certain age one stands still and stagnates.'),
  array('id' => '83','quote' => 'Advice in old age is foolish for what can be more absurd than to increase our provisions for the road the nearer we approach to our journey\'s end.'),
  array('id' => '84','quote' => 'When grace is joined with wrinkles'),
  array('id' => '85','quote' => 'It takes a long time to become young.'),
  array('id' => '86','quote' => 'After thirty'),
  array('id' => '87','quote' => 'There is a fountain of youth: it is your mind'),
  array('id' => '88','quote' => 'Age is not a particularly interesting subject. Anyone can get old. All you have to do is live long enough.'),
  array('id' => '89','quote' => 'Old minds are like old horses you must exercise them if you wish to keep them in working order.'),
  array('id' => '90','quote' => 'Forty is the old age of youth'),
  array('id' => '91','quote' => 'Youth is the gift of nature'),
  array('id' => '92','quote' => 'Preparation for old age should begin not later than one\'s teens. A life which is empty of purpose until 65 will not suddenly become filled on retirement.'),
  array('id' => '93','quote' => 'There is always some specific moment when we become aware that our youth is gone but'),
  array('id' => '94','quote' => 'Growing old is no more than a bad habit which a busy person has no time to form.'),
  array('id' => '95','quote' => 'As long as any adult thinks that he'),
  array('id' => '96','quote' => 'Old age is fifteen years older than I am.'),
  array('id' => '97','quote' => 'Aging is not lost youth but a new stage of opportunity and strength.'),
  array('id' => '98','quote' => 'The great secret that all old people share is that you really haven\'t changed in seventy or eighty years. Your body changes'),
  array('id' => '99','quote' => 'The trick is growing up without growing old.'),
  array('id' => '100','quote' => 'Old age comes on suddenly'),
  array('id' => '101','quote' => 'I think your whole life shows in your face and you should be proud of that.'),
  array('id' => '102','quote' => 'I\'m happy to report that my inner child is still ageless.'),
  array('id' => '103','quote' => 'Youth is the best time to be rich'),
  array('id' => '104','quote' => 'It is sad to grow old but nice to ripen.'),
  array('id' => '105','quote' => 'One of the many things nobody ever tells you about middle age is that it\'s such a nice change from being young.'),
  array('id' => '106','quote' => 'After you\'re older'),
  array('id' => '107','quote' => 'You end up as you deserve. In old age you must put up with the face'),
  array('id' => '108','quote' => 'I\'m not interested in age. People who tell me their age are silly. You\'re as old as you feel.'),
  array('id' => '109','quote' => 'Inflation is when you pay fifteen dollars for the ten-dollar haircut you used to get for five dollars when you had hair.'),
  array('id' => '110','quote' => 'My notion of a wife at 40 is that a man should be able to change her'),
  array('id' => '111','quote' => 'As you age naturally'),
  array('id' => '112','quote' => 'Old age is like a plane flying through a storm. Once you\'re aboard'),
  array('id' => '113','quote' => 'In youth the days are short and the years are long. In old age the years are short and day\'s long.'),
  array('id' => '114','quote' => 'The aging process has you firmly in its grasp if you never get the urge to throw a snowball.'),
  array('id' => '115','quote' => 'Age is how we determine how valuable you are.'),
  array('id' => '116','quote' => 'Middle age is when your age starts to show around your middle.'),
  array('id' => '117','quote' => 'Aging seems to be the only available way to live a long life.'),
  array('id' => '118','quote' => 'I think when the full horror of being fifty hits you'),
  array('id' => '119','quote' => 'To keep the heart unwrinkled'),
  array('id' => '120','quote' => 'If you\'re old'),
  array('id' => '121','quote' => 'Old age is an excellent time for outrage. My goal is to say or do at least one outrageous thing every week.'),
  array('id' => '122','quote' => 'I want to get old gracefully. I want to have good posture'),
  array('id' => '123','quote' => 'You know you\'re getting old when all the names in your black book have M. D. after them.'),
  array('id' => '124','quote' => 'What makes old age so sad is not that our joys but our hopes cease.'),
  array('id' => '125','quote' => 'Old age is a shipwreck.'),
  array('id' => '126','quote' => 'While one finds company in himself and his pursuits'),
  array('id' => '127','quote' => 'To resist the frigidity of old age'),
  array('id' => '128','quote' => 'Old age is the most unexpected of all the things that can happen to a man.'),
  array('id' => '129','quote' => 'No one can avoid aging'),
  array('id' => '130','quote' => 'If you haven\'t turned rebel by twenty you\'ve got no heart if you haven\'t turned establishment by thirty you\'ve got no brains!'),
  array('id' => '131','quote' => 'Oh rage! Oh despair! Oh age'),
  array('id' => '132','quote' => 'I don\'t want to fight aging I want to take good care of myself'),
  array('id' => '133','quote' => 'Middle age is the time when a man is always thinking that in a week or two he will feel as good as ever.'),
  array('id' => '134','quote' => 'We should so provide for old age that it may have no urgent wants of this world to absorb it from meditation on the next. It is awful to see the lean hands of dotage making a coffer of the grave.'),
  array('id' => '135','quote' => 'Middle age is the awkward period when Father Time starts catching up with Mother Nature.'),
  array('id' => '136','quote' => 'Middle age is youth without levity'),
  array('id' => '137','quote' => 'No man is ever old enough to know better.'),
  array('id' => '138','quote' => 'The denunciation of the young is a necessary part of the hygiene of older people'),
  array('id' => '139','quote' => 'In youth we run into difficulties. In old age difficulties run into us.'),
  array('id' => '140','quote' => 'We pay when old for the excesses of youth.'),
  array('id' => '141','quote' => 'The answer to old age is to keep one\'s mind busy and to go on with one\'s life as if it were interminable. I always admired Chekhov for building a new house when he was dying of tuberculosis.'),
  array('id' => '142','quote' => 'We\'ve put more effort into helping folks reach old age than into helping them enjoy it.'),
  array('id' => '143','quote' => 'The real sadness of fifty is not that you change so much but that you change so little.'),
  array('id' => '144','quote' => 'I\'m not afraid of aging.'),
  array('id' => '145','quote' => 'He has a profound respect for old age. Especially when it\'s bottled.'),
  array('id' => '146','quote' => 'Whatever poet'),
  array('id' => '147','quote' => 'To keep the heart unwrinkled'),
  array('id' => '148','quote' => 'In old age we are like a batch of letters that someone has sent. We are no longer in the past'),
  array('id' => '149','quote' => 'There\'s no such thing as old age')
);
